"""init tables

Revision ID: 2eba72c3ea8a
Revises: 
Create Date: 2025-08-13 10:38:49.671776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eba72c3ea8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adherents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adherents_email'), 'adherents', ['email'], unique=True)
    op.create_index(op.f('ix_adherents_id'), 'adherents', ['id'], unique=False)
    op.create_table('livres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_livres_id'), 'livres', ['id'], unique=False)
    op.create_index(op.f('ix_livres_title'), 'livres', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_livres_title'), table_name='livres')
    op.drop_index(op.f('ix_livres_id'), table_name='livres')
    op.drop_table('livres')
    op.drop_index(op.f('ix_adherents_id'), table_name='adherents')
    op.drop_index(op.f('ix_adherents_email'), table_name='adherents')
    op.drop_table('adherents')
    # ### end Alembic commands ###
