"""auth fields

Revision ID: c0f3d3583ea6
Revises: 2eba72c3ea8a
Create Date: 2025-08-14 18:12:09.406594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0f3d3583ea6'
down_revision: Union[str, Sequence[str], None] = '2eba72c3ea8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adherents', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.alter_column('adherents', 'email',
               existing_type=sa.VARCHAR(length=180),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_column('adherents', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adherents', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('adherents', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=180),
               existing_nullable=False)
    op.drop_column('adherents', 'password_hash')
    # ### end Alembic commands ###
